iframe_domain_url: "http://www.holachef.com"
citrus_gateway:
  gateway_env : 'sandbox'     # options - sandbox, staging or production
  pmturl : 'h5omh3rcch'	# as per citrus pay merchant setup
  accesskey : '81HWEZWD41VN6NHDNNGB' # as per citrus pay merchant setup
  apikey : '573f85c0b61fdc202e3cff60b1c8333b5736a2e9' # as per citrus pay merchant setup
  action : 'http://www.holachef.com/orders/callback' # change it as required by your app...
  returnUrl : ' http://www.holachef.com/orders/callback'
